### ISSUE TITLE
Outdated documentation w.r.t. user accounts

### ISSUE THREAD

**Issue by rlaurika** [CSCfi/pouta-virtualcluster#1]
The login instructions in the README have instructions for logging in as root. However, the root account is no longer directly accessible on the images in cPouta. Instead, you should login as either cloud-user or ubuntu depending on the image. Passwordless root access can be gained by prepending "sudo" to commands or with "sudo -i".

You could add instructions to use sudo and remove reference to logging in as root or the centos user (which does not exist in any of the images we provide).

**Comment by tourunen** [comment]
Readme has been updated to reflect the improved login procedure of cPouta base images
